name: bearing
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch::pytorch=2.0.1
  - pytorch::torchvision=0.15.2
  - pytorch::pytorch-cuda=11.7
  - conda-forge::gdown=4.7.1
  - conda-forge::matplotlib=3.8.0
  - conda-forge::numpy=1.26.0
  - conda-forge::pandas=2.1.0
  - conda-forge::python=3.11.5
  - conda-forge::scipy=1.11.2
  - conda-forge::tqdm=4.66.1