name: bearing
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch::pytorch=2.0
  - pytorch::torchvision=0.15
  - pytorch::pytorch-cuda=11.7
  - conda-forge::black=23.11
  - conda-forge::mypy=1.7
  - conda-forge::gdown=4.7
  - conda-forge::matplotlib=3.8
  - conda-forge::numpy=1.26
  - conda-forge::pandas=2.1
  - conda-forge::pandas-stubs=2.1
  - conda-forge::python=3.11
  - conda-forge::scikit-learn=1.3
  - conda-forge::scipy=1.11
  - conda-forge::tqdm=4.66